name: Hadolint

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'

jobs:
  dockerfile-lint:
    name: Lint Dockerfile with Hadolint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
